---
title: "Quiz: Interpreting Coefficients"
author: "Nicholas Reich, adapted from Project MOSAIC"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
```

The quiz is available at: <http://goo.gl/forms/VjWJKTZLVV>

## Overview

We will load the data set JAMA-HR.csv which contains data from a report in the Journal of the American Medical Association. Each case is an individual person. The variables are 

 - Temp: body temperature in degrees F 
 - HR: heart rate in beats per minute
 - Sex: coded as F and M

```{r, message=FALSE}
jama = fetch::fetchData("JAMA-HR.csv")
nrow(jama)
head(jama)
```

```{r plotData, fig.height=3, echo=FALSE}
ggplot(jama, aes(x=Temp, y=HR)) + geom_point(aes(shape=Sex, color=Sex))
```


## Models
Here are several different model outputs for you to consider.

```{r}
mod1 = lm(HR ~ 1, data=jama) 
coef(mod1)
mod2 = lm(HR ~ Temp, data=jama) 
coef(mod2)
mod3 = lm(HR ~ Sex, data=jama) 
coef(mod3)
mod4 = lm(HR ~ Temp + Sex, data=jama) 
coef(mod4)
mod5 = lm(HR ~ Sex * Temp, data=jama) 
coef(mod5)
c(AIC(mod1), AIC(mod2), AIC(mod3), AIC(mod4), AIC(mod5))
```

